WebApplication1/Models/Category.cs
namespace WebApplication1.Models
{
    public class Category
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public List<Product> Products {  get; set; }
        public Category() { }
        public Category(string name) 
        {
            Name = name;
        }
    }
}

WebApplication1/Models/ErrorViewModel.cs
namespace WebApplication1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication1/Models/Product.cs
namespace WebApplication1.Models
{
    public class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Price { get; set; }
        public int Quantity { get; set; }
        public int CategoryId { get; set; }
        public Category Category { get; set; }
        public int UserId { get; set; }
        public User User { get; set; }
        public Product() { }
        public Product( string name, int price, int quantity,Category category)
        {
            Name = name;
            Price = price;
            Quantity = quantity;
            Category = category;
        }
    }
}

WebApplication1/Models/User.cs
namespace WebApplication1.Models
{
    public class User
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int Age { get; set; }
        public List<Product> Products { get; set; }  
        public User() { }
        public User (string name,string email,string password,int age) 
        {
            Name = name;
            Email = email;
            Password = password;
            Age = age;
        }
        public string GetPassword(string password)
        {
            if(password == Password)
            {
                return Password;
            }
            return " ";
        }
    }
}

WebApplication1/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Appsrc.DataBase;
using WebApplication1.Appsrc.Service;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class CategoryController : Controller
    {
        private CategoryService categoryService = new CategoryService();

		public IActionResult Index()
        { 
            if (OnlineUser.Onlineuser is null)
            {
                return RedirectToAction("Error");
            }
            return View(categoryService.GetAllCategories());
        }

        public IActionResult Create()
        {
            Category category = new Category();
            return View(category);
        }
        [HttpPost]
        public IActionResult Create(Category category)
        {
           categoryService.AddCategory(category.Name);
            return RedirectToAction("Index");
        }
    }
}

WebApplication1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplication1.Appsrc.DataBase;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View(OnlineUser.Onlineuser);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            var error = new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier };
            return View(error);
        }
    }
}

WebApplication1/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplication1.Appsrc.DataBase;
using WebApplication1.Appsrc.Service;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class ProductController : Controller
    {
        private ProductService ProductService = new ProductService();
        public IActionResult Index()
        {
            if (OnlineUser.Onlineuser is null)
            {
                return RedirectToAction("Error");
            }
            return View(ProductService.GetAllProducts());
        }

    }
}

WebApplication1/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using WebApplication1.Appsrc.Service;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class UserController : Controller
    {
        UserService userService = new UserService();    
        public IActionResult Index()
        {
            return View(userService.GetAllUsers());
        }
        
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateUser(string name, string email,string password, int age)
        {

           bool isdone =  userService.Register(name, email, password, age);
            return RedirectToAction("Index");
        }
        public IActionResult Login() 
        { 
            return View(); 
        }
        [HttpPost]
        public IActionResult Login(string email, string password)
        {
            bool isdone = userService.login(email, password);
            return RedirectToAction("Index", "Home");
        }
  
    }
}

WebApplication1/Views/Category/Create.cshtml
@model Category

<div class="container">
    <form method="post" asp-action="CreateCategory">
        <div class="form-floating mb-3">
            <input class="form-control" name="name" type="text" placeholder="Enter new category..." data-sb-validations="required" />
            <label for="category">Category</label>
        </div>
        <div class="d-grid">
            <button class="btn btn-primary  btn-lg" id="submitButton" type="submit">
                Create
            </button>
        </div>
    </form>

</div>

WebApplication1/Views/Category/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model List<Category>
<div class="table-responsive">
    <table class="table table-striped table-hover table-bordered table-sm ">
        <caption>Shop Categories</caption>
        <thead>
            <tr class="bg-success">
                <th scope="col">Id</th>
                <th scope="col">Name</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var category in @Model)
            {
                <tr>
                    <th scope="row">@category.Id</th>
                    <td>@category.Name</td>
                </tr>
            }
        </tbody>
    </table>

        <a class="btn btn-success" type="button" asp-action="Create">Create New Category</a>


</div>

WebApplication1/Views/Home/Index.cshtml
@using WebApplication1.Appsrc.DataBase
@model User
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center" style="background-color:antiquewhite; border-radius:6px; height:100vh;">
    <h1 class="display-4">Welcome to the Online Store!!</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    @if (Model is not null)
    {
        <p class="display-3">Current Online User: @Model.Name</p>
    }
    @if(true)
    {}
</div>

WebApplication1/Views/Product/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model List<Product>
@if(@Model != null)
{
    <div class="table-responsive">
        <table class="table table-striped table-hover table-bordered table-sm ">
            <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Name</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Price</th>
                    <th scope="col">Category</th>
                    <th scope="col">User</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var product in @Model)
                {
                    <tr>
                        <th>@product.Id</th>
                        <td>@product.Name</td>
                        <td>@product.Quantity</td>
                        <td>@product.Price</td>
                        <td>@product.Category.Name</td>
                        <td>@product.User.Name</td>
                    </tr>
                }
            </tbody>

        </table>
    </div>
}
else
{
    Layout = "Error";
}

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
    <style>
        #bt:hover{
            background-image: linear-gradient(135deg,rgb(70, 205, 122),rgb(0, 162, 255));
        } 
        #bt{
            background-image: linear-gradient(135deg,rgb(26, 132, 67),rgb(9, 71, 107));
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                        <li id="bt" class="nav-item float-end btn-outline-light " style="border-radius:10px; margin-left:auto;">
                            <a  class="nav-link text-light" asp-area="" asp-controller="User" asp-action="Login">
                                Login
                                </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebApplication1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApplication1/Views/User/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model List<User>

<div class="table-responsive">
    <table class="table table-striped table-hover table-bordered table-sm ">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Email</th>
                <th>Age</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var user in @Model)
            {
                <tr>
                    <th>@user.Id</th>
                    <td>@user.Name</td>
                    <td>@user.Email</td>
                    <td>@user.Age</td>
                </tr>
            }
        </tbody>

    </table>
</div>

WebApplication1/Views/User/Login.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Page</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-image: linear-gradient(135deg,rgb(70, 205, 122),rgb(0, 162, 255));
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .container {
            background-color: #ffffff;
            border-radius: 8px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            padding: 20px 30px;
            width: 100%;
            max-width: 400px;
        }

            .container h2 {
                text-align: center;
                margin-bottom: 20px;
                color: #333;
            }

        .form-group {
            margin-bottom: 15px;
        }

            .form-group label {
                display: block;
                margin-bottom: 5px;
                font-weight: bold;
                color: #555;
            }

            .form-group input {
                width: 100%;
                padding: 10px;
                border: 1px solid #ddd;
                border-radius: 5px;
                font-size: 16px;
            }

                .form-group input:focus {
                    outline: none;
                    border-color: #4a90e2;
                    box-shadow: 0 0 5px rgba(74, 144, 226, 0.3);
                }

        .btn {
            display: block;
            width: 100%;
            padding: 10px;
            background-color: #4a90e2;
            border: none;
            border-radius: 5px;
            font-size: 16px;
            color: white;
            font-weight: bold;
            cursor: pointer;
            margin-top: 10px;
        }

            .btn:hover {
                background-color: #357ab7;
            }

        .note {
            text-align: center;
            margin-top: 10px;
            font-size: 14px;
            color: #777;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>Login</h2>
        <form asp-action="Login" method="post">
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" id="email" name="email" placeholder="Enter your email" required>
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" id="password" name="password" placeholder="Enter your password" required>
            </div>
            <button type="submit" class="btn">Login</button>
        </form>
        <p class="note">Don't have an account? <a asp-area="" asp-action="Register">Register here</a>.</p>
    </div>
</body>
</html>

WebApplication1/Views/User/Register.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register Page</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-image: linear-gradient(135deg,rgb(70, 133, 205),rgb(255, 0, 238));
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .container {
            background-color: #ffffff;
            border-radius: 8px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            padding: 20px 30px;
            width: 100%;
            max-width: 400px;
        }

        .container h2 {
            text-align: center;
            margin-bottom: 20px;
            color: #333;
        }

        .form-group {
            margin-bottom: 15px;
        }

        .form-group label {
            display: block;
            margin-bottom: 5px;
            font-weight: bold;
            color: #555;
        }

        .form-group input {
            width: 100%;
            padding: 10px;
            border: 1px solid #ddd;
            border-radius: 5px;
            font-size: 16px;
        }

        .form-group input:focus {
            outline: none;
            border-color: #4a90e2;
            box-shadow: 0 0 5px rgba(74, 144, 226, 0.3);
        }

        .btn {
            display: block;
            width: 100%;
            padding: 10px;
            background-color: #4a90e2;
            border: none;
            border-radius: 5px;
            font-size: 16px;
            color: white;
            font-weight: bold;
            cursor: pointer;
            margin-top: 10px;
        }

        .btn:hover {
            background-color: #357ab7;
        }

        .note {
            text-align: center;
            margin-top: 10px;
            font-size: 14px;
            color: #777;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>Register</h2>
        <form asp-action="CreateUser" method="post">
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" id="name" name="name" placeholder="Enter your name" required>
            </div>
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" id="email" name="email" placeholder="Enter your email" required>
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" id="password" name="password" placeholder="Enter your password" required>
            </div>
            <div class="form-group">
                <label for="age">Age</label>
                <input type="number" id="age" name="age" placeholder="Enter your age" required>
            </div>
            <button type="submit" class="btn">Register</button>
        </form>
        <p class="note">Already have an account? <a asp-area="" asp-action="Login">Login here</a>.</p>
    </div>
</body>
</html>